import {useState} from 'react'
import {ArrowUpRight, Menu, X} from 'lucide-react'
import {useLanguage} from '../Language.jsx'
const links=[['Home','#home'],['Services','#services'],['Portfolio','#portfolio'],['Pricing','#pricing'],['FAQ','#faq'],['About','#about'],['Contact','#contact']]
export default function Header(){
 const [open,setOpen]=useState(false)
 const {lang,setLang,t}=useLanguage()
 return <div className="sticky top-0 z-40 shadow-sm">
   <div className="bg-forest text-white"><div className="mx-auto max-w-[1500px] px-5 md:px-10 flex min-h-10 items-center justify-between gap-3 text-[11px] sm:text-xs font-semibold tracking-[.08em] uppercase"><span>{t('25% off interior renovation')} <span className="hidden sm:inline text-white/50 mx-2">/</span><span className="hidden sm:inline text-white/70">{t('A limited offer')}</span></span><div className="flex items-center gap-4"><a className="hidden sm:inline hover:text-gold" href="tel:+923061308197">0306-1308197</a><a href="#contact" className="text-[#ead1a0] hover:text-white">{t('Book now')} <ArrowUpRight size={13} className="inline"/></a></div></div></div>
   <nav aria-label="Main navigation" className="bg-paper/95 backdrop-blur-xl border-b border-forest/10"><div className="mx-auto max-w-[1500px] px-5 md:px-10 h-[74px] flex justify-between items-center gap-6"><a href="#home" className="flex items-center gap-3 shrink-0" onClick={()=>setOpen(false)}><img src="/assets/logo.png" alt="Nqarchitects logo" className="w-12 h-12 object-contain"/><span className="font-semibold tracking-[.14em] uppercase text-forest text-sm">Nqarchitects</span></a><div className="hidden lg:flex items-center gap-5">{links.map(([n,h])=><a key={n} className="text-sm font-medium text-ink/70 hover:text-forest transition" href={h}>{t(n)}</a>)}</div><div className="flex items-center gap-3 ml-auto lg:ml-0"><div className="flex border border-forest/20 text-xs font-bold" aria-label="Language"><button onClick={()=>setLang('ES')} aria-pressed={lang==='ES'} className={`px-2.5 py-2 ${lang==='ES'?'bg-forest text-white':'text-forest'}`}>ES</button><button onClick={()=>setLang('EN')} aria-pressed={lang==='EN'} className={`px-2.5 py-2 ${lang==='EN'?'bg-forest text-white':'text-forest'}`}>EN</button></div><a href="#contact" className="hidden lg:inline-flex items-center gap-2 bg-forest px-5 py-3 text-white text-sm hover:bg-[#393b39] transition">{t('Free survey')} <ArrowUpRight size={16}/></a><button type="button" className="lg:hidden p-2" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>
   {open&&<div className="lg:hidden border-t bg-paper px-5 pb-6 pt-3 flex flex-col gap-1">{links.map(([n,h])=><a key={n} href={h} onClick={()=>setOpen(false)} className="py-3 border-b border-forest/10 text-forest">{t(n)}</a>)}<a href="#contact" onClick={()=>setOpen(false)} className="mt-3 bg-forest text-white px-4 py-3 text-center">{t('Free survey')}</a></div>}</nav>
 </div>
}
