import {useEffect,useState} from 'react'
import {ArrowDown,ArrowLeft,ArrowRight,ArrowUpRight} from 'lucide-react'
import {image} from '../data/content'
import {useLanguage} from '../Language.jsx'
const slides=[
 {image:'121106',eyebrow:'Architecture / Lahore',sub:'Spaces that make an impression long before you step inside.',position:'center'},
 {image:'121337',eyebrow:'Interior design',sub:'Designed around the way you want to live.',position:'center'},
 {image:'121411',eyebrow:'Considered luxury',sub:'Where expressive details find a sense of balance.',position:'center'},
 {image:'121454',eyebrow:'Residential architecture',sub:'A lasting vision for the place you call home.',position:'center'},
]
export default function Hero(){const {t}=useLanguage();const [index,setIndex]=useState(0);const [paused,setPaused]=useState(false);useEffect(()=>{if(paused)return;const id=setInterval(()=>setIndex(i=>(i+1)%slides.length),5500);return()=>clearInterval(id)},[paused]);const move=d=>setIndex(i=>(i+d+slides.length)%slides.length)
return <section id="home" aria-label="Featured projects" className="relative bg-forest text-white h-[620px] min-h-[580px] max-h-[850px] md:h-[78vh] overflow-hidden" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)}>
 {slides.map((slide,i)=><img key={slide.image} src={image(slide.image)} alt={t(slide.eyebrow)} fetchPriority={i===0?'high':undefined} className={`absolute inset-0 w-full h-full object-cover transition-opacity duration-1000 ${i===index?'opacity-100':'opacity-0'}`} style={{objectPosition:slide.position}} aria-hidden={i!==index}/>)}
 <div className="absolute inset-0 bg-gradient-to-r from-[#151715]/80 via-[#151715]/45 to-black/10"/><div className="absolute inset-0 bg-gradient-to-t from-[#151715]/55 via-transparent to-transparent"/>
 <div className="relative z-10 mx-auto max-w-[1500px] px-5 md:px-10 h-full flex flex-col justify-center pb-20"><div className="flex items-center gap-4 text-xs tracking-[.25em] uppercase text-[#ebd1a0] font-semibold"><span className="h-px w-10 bg-gold"/>NQArchitects <span className="hidden sm:inline">/ {t(slides[index].eyebrow)}</span></div><h1 className="font-display leading-[1.09] text-[clamp(3.1rem,7.4vw,7.7rem)] max-w-[900px] mt-6">{t('Transform your space')} <em className="font-normal text-[#e8d2ad]">{t('into your dream.')}</em></h1><p className="text-base sm:text-lg text-white/85 max-w-md mt-6 leading-relaxed">{t(slides[index].sub)}</p><div className="flex flex-wrap gap-4 mt-9"><a href="#contact" className="inline-flex gap-4 items-center justify-between bg-[#e3c485] hover:bg-white hover:text-forest text-forest px-6 py-4 min-w-[235px] transition font-semibold text-sm">{t('Book free consultation')} <ArrowUpRight size={18}/></a><a href="#portfolio" className="inline-flex items-center gap-3 py-4 px-2 border-b border-white/70 text-sm font-semibold hover:text-[#e3c485]">{t('Explore our work')} <ArrowDown size={16}/></a></div></div>
 <div className="absolute bottom-0 left-0 right-0 z-10"><div className="mx-auto max-w-[1500px] px-5 md:px-10 pb-7 flex justify-between items-center"><span className="text-xs tracking-[.2em]">0{index+1} <span className="text-white/50">/ 0{slides.length}</span></span><div className="flex gap-2" aria-label="Choose slide">{slides.map((s,i)=><button key={s.image} onClick={()=>setIndex(i)} aria-label={`Show slide ${i+1}`} aria-current={i===index?'true':undefined} className={`h-1 transition-all ${i===index?'w-10 bg-[#e3c485]':'w-5 bg-white/50 hover:bg-white'}`}/>)}</div><div className="flex gap-2"><button onClick={()=>move(-1)} aria-label="Previous slide" className="w-10 h-10 grid place-items-center border border-white/55 hover:bg-white hover:text-forest"><ArrowLeft size={17}/></button><button onClick={()=>move(1)} aria-label="Next slide" className="w-10 h-10 grid place-items-center border border-white/55 hover:bg-white hover:text-forest"><ArrowRight size={17}/></button></div></div></div>
 </section>}
