import {useState} from 'react'
import {ArrowUpRight,Plus,Minus} from 'lucide-react'
import {useLanguage} from '../Language.jsx'

const advantages=[['Listen first','We start with how you use the space and what matters to you.'],['See it before it is built','3D planning helps clarify the design before execution.'],['Details in harmony','Materials, lighting and finishing are considered together.']]
const packages=[['Initial survey','Free','Discuss goals, space and next steps.'],['Design & planning','Custom quote','Concept, layout and 3D planning as needed.'],['Renovation & execution','Custom quote','Materials, finishes and on-site work tailored to the brief.']]
const questions=[['Is the initial survey free?','Yes. Contact the team to arrange a free initial survey and discuss your project.'],['How is the price calculated?','A quote is prepared after reviewing the area, design scope, materials and required work.'],['Can I see the design before work begins?','3D design and planning are available to help you review the proposed space before execution.'],['Where is the studio located?','Nqarchitects is based at E180 DHA, Lahore, Pakistan.']]

export function WhyUs(){const {t}=useLanguage();return <section id="why-us" className="bg-[#f3f0eb] py-20 md:py-28"><div className="max-w-[1500px] mx-auto px-5 md:px-10"><p className="eyebrow">{t('Why Nqarchitects')} <span>/ 03</span></p><h2 className="section-title mt-4">{t('A vision built')} <em>{t('around you.')}</em></h2><div className="grid md:grid-cols-3 gap-6 mt-12">{advantages.map(([title,body],i)=><article key={title} className="border-t border-forest/25 pt-6"><span className="text-sm text-gold font-semibold">0{i+1}</span><h3 className="font-display text-2xl mt-7 text-forest">{t(title)}</h3><p className="mt-3 text-ink/65 leading-7">{t(body)}</p></article>)}</div></div></section>}

export function Pricing(){const {t,lang}=useLanguage();const [area,setArea]=useState(500),[rate,setRate]=useState(1500);const a=Math.max(0,Number(area)||0),r=Math.max(0,Number(rate)||0);const total=a*r;const fmt=new Intl.NumberFormat(lang==='ES'?'es-ES':'en-PK',{maximumFractionDigits:0});return <section id="pricing" className="bg-paper py-20 md:py-28"><div className="max-w-[1500px] mx-auto px-5 md:px-10"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-8"><div><p className="eyebrow">{t('Pricing')} <span>/ 04</span></p><h2 className="section-title mt-4">{t('Clear scope.')} <em>{t('A tailored quote.')}</em></h2></div><p className="max-w-sm leading-7 text-ink/65">{t('Each project is quoted after understanding the space, materials and scope.')}</p></div><div className="grid lg:grid-cols-3 gap-4 mt-11">{packages.map(([title,price,desc],i)=><div key={title} className={`border border-forest/15 p-7 md:p-9 flex flex-col min-h-64 ${i===0?'bg-forest text-white':'bg-white'}`}><span className={`text-xs uppercase tracking-[.2em] ${i===0?'text-[#dec79b]':'text-gold'}`}>0{i+1}</span><h3 className="font-display text-2xl mt-8">{t(title)}</h3><p className="text-xl font-semibold mt-3">{t(price)}</p><p className={`text-sm mt-3 leading-relaxed ${i===0?'text-white/70':'text-ink/60'}`}>{t(desc)}</p><a href="#contact" className="mt-auto pt-6 inline-flex items-center gap-2 text-sm font-semibold">{t('Request a quote')} <ArrowUpRight size={15}/></a></div>)}</div>
<div id="estimator" className="mt-12 bg-[#ebe6dd] grid lg:grid-cols-2 gap-8 lg:gap-16 p-7 md:p-12"><div><p className="eyebrow">{t('Planning budget calculator')}</p><h3 className="font-display text-3xl md:text-4xl mt-4 text-forest">{t('Make a budget plan')}</h3><p className="mt-4 text-ink/65 leading-7">{t('Enter your own target spend per square foot to see a planning total. This is your budget, not an Nqarchitects quote.')}</p><p className="mt-6 text-sm text-ink/55">{t('Final price depends on site conditions, design, materials and agreed scope.')}</p></div><div className="bg-white p-6 md:p-8 border border-forest/10"><div className="grid sm:grid-cols-2 gap-4"><label className="field-label">{t('Area (sq ft)')}<input type="number" min="1" max="100000" step="1" value={area} onChange={e=>setArea(e.target.value)} className="field"/></label><label className="field-label">{t('Target budget per sq ft (PKR)')}<input type="number" min="1" max="1000000" step="50" value={rate} onChange={e=>setRate(e.target.value)} className="field"/></label></div><div className="border-t border-forest/15 mt-7 pt-6"><span className="text-xs uppercase tracking-widest text-ink/55">{t('Your planning budget')}</span><p role="status" className="font-display text-4xl md:text-5xl text-forest mt-2">PKR {fmt.format(total)}</p><p className="text-xs text-ink/50 mt-2">{fmt.format(a)} sq ft × PKR {fmt.format(r)}</p></div><a href="#contact" className="inline-flex items-center gap-3 mt-7 bg-forest text-white px-5 py-3 text-sm font-semibold hover:bg-[#393b39]">{t('Discuss this budget')} <ArrowUpRight size={16}/></a></div></div></div></section>}

export function FAQ(){const {t}=useLanguage();const [open,setOpen]=useState(0);return <section id="faq" className="bg-[#f3f0eb] py-20 md:py-28"><div className="max-w-[1500px] mx-auto px-5 md:px-10 grid lg:grid-cols-[.8fr_1.2fr] gap-10 lg:gap-20"><div><p className="eyebrow">FAQ <span>/ 05</span></p><h2 className="section-title mt-4">{t('Good to know')}.</h2></div><div className="border-t border-forest/20">{questions.map(([q,a],i)=><div key={q} className="border-b border-forest/20"><button aria-expanded={open===i} onClick={()=>setOpen(open===i?-1:i)} className="w-full py-6 flex justify-between items-center text-left gap-6 text-lg font-semibold text-forest"><span>{t(q)}</span>{open===i?<Minus className="shrink-0" size={18}/>:<Plus className="shrink-0" size={18}/>}</button>{open===i&&<p className="pb-7 pr-8 text-ink/65 leading-7">{t(a)}</p>}</div>)}</div></div></section>}
